// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWkjycnFmHSXBLRfqxzGqyjbBcZ0V37M',
    appId: '1:357232841490:android:bf8abd6e40c8560a6f99cb',
    messagingSenderId: '357232841490',
    projectId: 'yelta-innovation-1',
    databaseURL: 'https://yelta-innovation-1-default-rtdb.firebaseio.com',
    storageBucket: 'yelta-innovation-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpm6aPpUtdkQuu0PsZ-kToPRJpCLBxjzM',
    appId: '1:357232841490:ios:a9402bfc428e4e356f99cb',
    messagingSenderId: '357232841490',
    projectId: 'yelta-innovation-1',
    databaseURL: 'https://yelta-innovation-1-default-rtdb.firebaseio.com',
    storageBucket: 'yelta-innovation-1.firebasestorage.app',
    iosBundleId: 'com.example.travelci',
  );
}
